### ISSUE TITLE
Error: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by Nataliya1** [Esri/land-use-public-notification#87]
Hi,

While trying to query my street layer, I am getting an error. I got the app working, but then I had to make some changes to my street layer, and now its not working any more. When I search for specific value from the search field in the street layer, its just keeps spinning and I am not getting results, the developer console shows the following error:

init.js:199 TypeError: Cannot read property 'toLowerCase' of undefined
    at http://dogis.org/mailing_labels/js/library/widgets/locator/locator.js:569:35
    at Array.sort (native)
    at Object._findDisplayRoad (http://dogis.org/mailing_labels/js/library/widgets/locator/locator.js:568:27)
    at Object._getUnifiedResult (http://dogis.org/mailing_labels/js/library/widgets/locator/locator.js:652:22)
    at Object.<anonymous> (http://dogis.org/mailing_labels/js/library/widgets/locator/locator.js:355:22)
    at http://js.arcgis.com/3.15/init.js:167:296
    at c (http://js.arcgis.com/3.15/init.js:66:221)
    at d (http://js.arcgis.com/3.15/init.js:66:10)
    at p.DeferredList.resolve.callback (http://js.arcgis.com/3.15/init.js:67:350)
    at n (http://js.arcgis.com/3.15/init.js:1551:35) 

Appreciate any help. Thanks, Nataliya

**Comment by ChrisBuscaglia** [comment]
@Nataliya1 if you can please contact [Esri Support Services](http://support.esri.com/en/) and supply your data, they will be more than happy to help you configure the application.

**Comment by Nataliya1** [comment]
@ChrisBuscaglia thank you. I was thinking about that. But I got it figured out. The issue was with my street layer. I had dissolved features (multi-part) features in my layer. And after I exploded the road features, and republished my service, the app started working. Thanks again.
